export const TAB_BAR_STYLE = {
  height: 54,
  paddingBottom: 4,
  paddingTop: 4,
  borderWidth: 1,
  borderColor: "#E6E9EF",
  backgroundColor: "#ffffff",
  position: "absolute",
  left: 24,
  right: 24,
  bottom: 60,
  borderRadius: 16,
  paddingHorizontal: 0,
  alignItems: "center",
  shadowColor: "#0F172A",
  shadowOpacity: 0.08,
  shadowRadius: 8,
  shadowOffset: { width: 0, height: 6 },
  elevation: 6,
  marginHorizontal: 34,
};
